apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo1-ingress
  namespace: test1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.fangcorp88.com
    secretName: fangcorp88-tls
  rules:
    - host: www.fangcorp88.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name:  demo1-helm-example
              port:
                number: 80
